#!/usr/bin/env sh

env_var="$1"

if [ -z "$env_var" ]; then
	echo "You need to specify an environment variable name." >&2
	exit 1
fi

secret=$(eval echo \$$env_var)
secret_file_var="${env_var}_FILE"
secret_file="${!secret_file_var}"

if [ -n "$secret" ]; then
	echo "$secret"
elif [ -n "$secret_file" ] && [ -f "$secret_file" ]; then
	cat "$secret_file"
else
	echo "Secret not found." >&2
	exit 1
fi
